### ISSUE TITLE
Tier Prices on Configurable Product Page

### ISSUE THREAD

**Issue by ladle3000** [sprankhub/Spranks_ConfigurableTierPrices#18]
When I change my selection in the dropdown the tier prices look like the attached...

![bumgenius 4 0 snaps](https://cloud.githubusercontent.com/assets/2366245/5945775/d7823c7e-a6fe-11e4-86c9-05fee76580bf.jpeg)

**Comment by sprankhub** [comment]
This is a known Magento bug and has nothing to do with my extension (if you disabe my extension, the problem will remain the same). If you google for it, you should find a solution like [this one here](https://stackoverflow.com/questions/13504056/magento-tier-prices-class-declaration-for-tier-price-in-buy-x-for-y-javascri).
