### ISSUE TITLE
Options with Fixed Price Producing Wrong Unit Price

### ISSUE THREAD

**Issue by refueledinc** [sprankhub/Spranks_ConfigurableTierPrices#19]
When options have a fixed price, the tier price is not applied.  

![shopping cart](https://cloud.githubusercontent.com/assets/6714989/6126658/c34ee7c4-b0f0-11e4-8a88-07bed3396147.png)

Only when the line item itself exceeds the minimum limit does the unit price change. 
![shopping cart2](https://cloud.githubusercontent.com/assets/6714989/6126748/b4eb94e2-b0f1-11e4-8639-4da4b13700b6.png)

Is this a bug or am I misunderstanding the abilities of the extension?

**Comment by sprankhub** [comment]
At a first glance, this should work.

1. Do you use the latest version 2.1.0? There were problems when using individual options prior to 1.0.1.
2. If you use the latest version, could you send me screenshots of the prices and individual options tab in the Magento admin for this product?

**Comment by refueledinc** [comment]
Thanks for the response.
1. Yes, it's the latest. I downloaded and installed the master branch yesterday.
2. See below.
![price](https://cloud.githubusercontent.com/assets/6714989/6145876/5a58bc08-b1b4-11e4-8bb8-97dcf9c19dfd.png)
![options](https://cloud.githubusercontent.com/assets/6714989/6145877/5c944eba-b1b4-11e4-857b-8f9137851128.png)

**Comment by sprankhub** [comment]
What is the type of the product? Is it a configurable product at all? Or is it a simple product? The extension only works for configurable products.

I have a paid extension which enables tier prices for simple products with custom options "in the pipeline" though.

**Comment by refueledinc** [comment]
Ahh, yes, this is a simple product. Any ETA on the paid extension?

**Comment by sprankhub** [comment]
The biggest problem is that I do not have an online shop in order to sell the extension. Hence, it probably still takes some time. But the extension is nearly finished, so I could send it to you in a few days. We just have to agree on a price ;) If you are interested, please contact me directly via mail. Contact information under http://simonsprankel.com
