### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by mattabsolute** [sprankhub/Spranks_ConfigurableTierPrices#20]
I have just installed the moduel and it doesn't appear to have had any affect. The following product has a tier price applied and only kicks in when multiples of the same variant have been installed: http://www.ostomart.co.uk/default/coversure-custom-made-100-tactel-pouch-covers

**Comment by sprankhub** [comment]
Please check https://github.com/sprankhub/Spranks_ConfigurableTierPrices#faq first. If this does not help, please send me admin access privately. Contact data under http://simonsprankel.de/

**Comment by sprankhub** [comment]
The problem was that the products also use custom options. Custom options are not supported by this extension. There will be a paid version which supports tier prices across products with custom options.
