### ISSUE TITLE
Configurable products

### ISSUE THREAD

**Issue by the-wanted** [sprankhub/Spranks_ConfigurableTierPrices#21]
Hello,
i need that the extension add the items with same colour but not add the different colour.
It is possible? I have items configurable with attribute size and colour.

http://www.atelierdelricamo.it/t-shirt-uomo-valueweight-manica-corta-fruit-of-the-loom.html

**Comment by sprankhub** [comment]
Please describe your issue in more detail. I do not get what you are trying to achieve...

**Comment by the-wanted** [comment]
Hello,
I set a different price for item if a customer buy 10 items. But when i add to cart 5 items in a colour and 5 items in another colour my site doesn't apply price for 10 items. 
Please see here
http://www.atelierdelricamo.it/t-shirt-uomo-original-screen-stars-fruit-of-the-loom.html
thanks

**Comment by sprankhub** [comment]
That should normally work - that is exactly the purpose of this extension. Please have a look at the [FAQs](https://github.com/sprankhub/Spranks_ConfigurableTierPrices#faq). If this does not help, you can send me admin information privately (mail address under http://simonsprankel.com) and I will have a look.

**Comment by Purostile** [comment]
Hello,
I've tried to install your extension (using Magento Connect), but don't work.
Then, I uninstall it (using Magento Connect), but "Disable Spranks Configurable Tier Prices" option still it remains in Product configuration. I've also tried to run the SQL query recommended by you... without results.
I should remove all files by hand?
Regards

Note: I'm using Magento 1.9.1.0

**Comment by sprankhub** [comment]
Next time, please open a new issue since this is totally unrelated to this issue.

I have no idea what did not work for you when installing/uninstalling the extension. Although you should not use the Magento Connect manager at all.

Executing the SQL command from https://github.com/sprankhub/Spranks_ConfigurableTierPrices#uninstallation and clearing the cache should be enough to remove the attribute from the product page.

**Comment by Purostile** [comment]
Thanks for your help.
1. Sorry, I'm newbie on Github!
2. Neither do I know what didn't work during installation/uninstallation. I simply used the usual procedure with Magento connect.
3. The SQL command you advice is the same that I used.
Do you advise me to repeat the installation?

**Comment by sprankhub** [comment]
Yeah, try to install again. If it does not work, first check the [FAQs](https://github.com/sprankhub/Spranks_ConfigurableTierPrices#faq). If it still does not work, open a new issue here or send me a mail.
