### ISSUE TITLE
My Magento store ignore this extension!

### ISSUE THREAD

**Issue by Purostile** [sprankhub/Spranks_ConfigurableTierPrices#22]
Hello,
I've just repeated the installation, then I've cleared the cache, then I've checked that every configuration about "Prinks Configurable Tier Prices" were activated, and normal price was higher than tier prices... but it don't work.
My Magento store continues to use normal price of configurable product instead of those from tier price table of simple products associated.
What am I doing wrong?
Regards

**Comment by sprankhub** [comment]
> My Magento store continues to use normal price of configurable product instead of those from tier price table of simple products associated.
That exactly is the problem. This extension will still take the tier prices from the configurable product. This is the way Magento works. You have to enter the tier prices in the configurable product. They will then be applied across different associated simple products.
