### ISSUE TITLE
Group Pricing

### ISSUE THREAD

**Issue by JCwonder1** [sprankhub/Spranks_ConfigurableTierPrices#23]
Does this pull customer group pricing from the simple products?

**Comment by sprankhub** [comment]
No

**Comment by JCwonder1** [comment]
Thanks for the quick response.  I am looking for some functionality that will pull simple products customer group pricing.  Do you think this can be modified to do this or is it best to start with something else.  If so I will bring it to the attention of my developer.  Sorry for the lack of knowledge here.

**Comment by sprankhub** [comment]
SimpleConfigurableProducts may support this, but is not developed any more, so I strongly advice against using it. BetterConfigurableProducts does pull data from the simple products, but does not support group prices. The only extension I know which may help you is http://www.webtexsoftware.com/customer-group-prices-magento-extension

**Comment by JCwonder1** [comment]
Hi Simon,

Thanks for the great info.  Will take your advice.  I will contact Webtex to see if there extension can help.  Have you had any experience with Webtex extensions?  Are they well developed?  I have had some extensions that were poorly developed in the past that hindered the performance of our site.  We use our site for a lot of business operations so performance is key.

Thanks for taking the time out to respond.

Best,
Joe

**Comment by sprankhub** [comment]
Not yet, no. I am currently considering the extension for a client, but could not have a look yet.

Cheers!
