### ISSUE TITLE
Module not working with currency switch for configurable tier price product

### ISSUE THREAD

**Issue by kevccy** [sprankhub/Spranks_ConfigurableTierPrices#24]
When the module is enable and cart have configurable tier price items switching currency will hang and bring up memory size exhausted (Memory Limit= 1024mb). Once the module is disable the switching currency works fine with configurable items in cart on main page and on cart page. I have look into the Observer.php and i think the problem causing this issue is from "private function _getAllVisibleItems()" 
"Mage::getSingleton('checkout/session')->getQuote()->getAllVisibleItems();" This is causing an infinite loop on collecting the items. I try to fix the issue rewriting this code but same result for spliting up the get checkout/session and getQuote to stop the infinite loop when changing the currency. Hope there will be a fix on this. Thanks

Regards

Kevin

**Comment by kevccy** [comment]
Here's the fixed version of the public function,

    private function _getAllVisibleItems()
    {		
        if (Mage::helper('spranks_configurabletierprices')->isAdmin()) {
		$quote = Mage::getSingleton('checkout/session')->getQuote();
		$adminquote = Mage::getSingleton('adminhtml/session_quote')->getQuote();
		$cartItems = $quote->getAllVisibleItems();
		$adminItems = $adminquote->getAllVisibleItems(); 
            return $adminItems;
        } else {
            return $cartItems;
        }
    }

Currency switch now works with the module, if anyone can tidy this code will be great. Thank for the module!

**Comment by sprankhub** [comment]
Thanks for the report. I still need to check the issue and will do that asap.

But your "fixed" function looks weird. `$cartItems` is not defined. Could you clarify what you are trying to do there?

**Comment by kevccy** [comment]
Thank you for looking into it,
$cartItems is just a name for the call to get the $quote->getAllVisibleItems (); Can be change to any other name for the call "$configItems" I changed the code because of the infinite loop "Mage::getSingleton('checkout/session')->getQuote()->getAllVisibleItems();"  which is causing the memory size exhausted or hangs on currency switch. What i did was just split the code to break the infinite loop the code is around the same as original but different view. I have subscribe to this issue and will await for your good news, Thank again!

**Comment by sprankhub** [comment]
I could reproduce the issue. I tried to come up with the best fix I can currently find. I now load the quote object if we are in the checkout process to avoid the infinite loop. Otherwise, I simply get the quote object from the checkout session.

@kevccy could you test the current master branch and give me feedback if it resolves the issue for you?

**Comment by kevccy** [comment]
Yes, have tested the master branch, the currency switch still hangs and memory size exhausted. I checked the code it could may well be on line 92: "return $quote->getAllVisibleItems();" that is causing the infinite loop. I try adding an instance for it but still not fix the issue, not sure where in the code that is still causing the infinite loop.

**Comment by sprankhub** [comment]
What is causing the infinite loop is `Mage::getSingleton('adminhtml/session_quote')->getQuote()`. But when we are in the checkout, we now load the quote directly and do not get it from the session. This solves the problem in my test environment. Could you please check the output of `Mage::app()->getRequest()->getRouteName()` when you switch the currency and tell me what it is?

**Comment by kevccy** [comment]
Fatal error: Allowed memory exhausted, "\app\code\core\Mage\Eav\Model\Entity\Collection\Abstract.php on line 1108"

**Comment by sprankhub** [comment]
This cannot be the output of `Mage::app()->getRequest()->getRouteName()`. Do you have a publicly available test system, where I can check it myself? Then please send the data to mail@simonsprankel.de. Otherwise, I think I cannot really help you any more.

**Comment by kevccy** [comment]
I got this code on Line:1088 "$select = implode(' UNION ALL ', $selects);" could it be something to do with this? I will test the code on another new setup to see if the error still remains, if not it may well be something on the website or database causing the issue.

**Comment by sprankhub** [comment]
As said, the only thing which would help me would be the output of `Mage::app()->getRequest()->getRouteName()` when you switch the currency. You could add a `var_dump(Mage::app()->getRequest()->getRouteName());` quick and dirty into my observer to see it.

**Comment by kevccy** [comment]
string(20) "configurablegridview"

**Comment by sprankhub** [comment]
This is the output if you change the currency in the checkout/cart? Sounds like you are switching the currency on another page...

**Comment by kevccy** [comment]
I think i may know where that could be causing the error, i have a module for configurable grid view. I will uninstall the module to see if works. I need a little time to test the issue, will let you know once i get the results shortly. Thanks

**Comment by kevccy** [comment]
Got the results, master code working now, it was one of the configurable grid module was using rewrote version of template/catalog/product/view/type/options/configurable.phtml , code all works fine now, Thanks for your help!

**Comment by sprankhub** [comment]
Glad that it works now :-)
