### ISSUE TITLE
only simple products are taken in account

### ISSUE THREAD

**Issue by damiendd** [sprankhub/Spranks_ConfigurableTierPrices#26]
Hi,

I configured a configurable product plus all the simple on the same rules, but it does not work. For a ra product you got 3%, it works when you take 25 of the same simple porduct but if you choose 13+12 it isn't working.
It used to work.

I send you all the details in a PM.

Thank you.
Damien.

**Comment by damiendd** [comment]
How can i send you the info ? i can't find any option to contact you

**Comment by sprankhub** [comment]
simonsprankel.com
