### ISSUE TITLE
Configurable Prices Do Not Work in Admin

### ISSUE THREAD

**Issue by derekclayton** [sprankhub/Spranks_ConfigurableTierPrices#27]
When creating an order via the admin it does not apply the configurable prices. Only works from the front-end. Any thoughts as to a fix?

**Comment by sprankhub** [comment]
This is fixed in any version >= 0.4.0. If it still does not work:

- Which Magento version?
- Which version of this extension?
- Which other extensions are installed?

**Comment by derekclayton** [comment]
2.1.0
After doing a little more digging, it is working if the configurable product is chosen, but not if the simple products under it are selected directly.

IE the configurable product is ACE-CONFIG, which contains ACE-CHERRY and ACE-APPLE.

If you select ACE-CONFIG and configure it for cherry and then for apple you are good.  If you select ACE-CHERRY and ACE-APPLE it does not combine the tier pricing.

**Comment by sprankhub** [comment]
Yeah, selecting the configurable product is the way Magento normally works. At least in the frontend. Magento adds the configured configurable product to the cart, NOT the simple product. I think we should stick to that. If the simple product is added, it is not totally clear that the user wants to have the pricing of the configurable product.

**Comment by derekclayton** [comment]
Agree with your assessment of what Magento wants and how the front-end works. But in the back-end (admin) it shows all products to the admins in the order form. Ostensibly to allow them to select all of the simple products and quantities at once. As opposed to adding them one at a time selecting different configurable/options each time.

It would be a very nice enhancement to add, hint-hint :-)

**Comment by sprankhub** [comment]
:smile: 

Sorry, but I will not fix it because of this:

> If the simple product is added, it is not totally clear that the user wants to have the pricing of the configurable product.

You should consider switching to Magento 2 - the pricing has completely been changed there. You can take the prices of the simple products there ;)

**Comment by derekclayton** [comment]
Would love to switch, but our testing with it so far indicates it is not ready for our use. Plans to migrate are set for early next year.
