### ISSUE TITLE
Configurable Tier Price

### ISSUE THREAD

**Issue by omgdwong** [sprankhub/Spranks_ConfigurableTierPrices#29]
Hi friend,

You have answered this question in https://github.com/sprankhub/Spranks_ConfigurableTierPrices/issues/15 but I am having the same issue. The extension for surcharge associated product does not exist anymore.

Product receives one set of tier pricing then another tier price another upon changing dropdown attribute.
Am looking for the Tier Pricing Table to update and reflect this properly prior to "Add to Cart". Currently cart price is changing properly.

Am using Magento 1.8.1 if that helps, appreciate your work.

**Comment by sprankhub** [comment]
I do not really get your issue. Surcharges for associated products is Magento standard. You can define them in the associated products tab of the configurable product. The prices of the associated simple products are normally NOT taken into account.

If there is still an issue, please describe it in more detail (best with an example).

**Comment by omgdwong** [comment]
Is it possible to have the tier pricing reflect the upgraded attribute's cost upon selection?

**Comment by sprankhub** [comment]
Not sure what you exactly mean. The tier pricing text is actually updated when you select an option with an additional cost:

![image](https://cloud.githubusercontent.com/assets/930199/23542047/43586fb2-ffeb-11e6-9c15-b788229b0bff.png)

When you now select "gelb", which is 2 EUR more expensive:

![image](https://cloud.githubusercontent.com/assets/930199/23542058/51d60f4a-ffeb-11e6-853b-e8f2c4ce3c6c.png)

**Comment by omgdwong** [comment]
Hey Simon,

You can view listingsigns.com/listings.html

Prices do not change upon selection 24x24 aluminum upgrade

**Comment by omgdwong** [comment]
My apologizes, correct link is listingsigns.com/listing.html

**Comment by sprankhub** [comment]
I think this has nothing to do with my extension. If you disable my extension completely under `app/etc/modules`, the issue is still the same, right?
