### ISSUE TITLE
Doesn't work for 1.9.3.2

### ISSUE THREAD

**Issue by kentpatrick** [sprankhub/Spranks_ConfigurableTierPrices#30]
As the title suggests this doesn't work for Magento CE 1.9.3.2 if your able to update i would appreciate it.

I have checked the module is enabled.
I have checked the disable category is set to "no category".
I have added price tiers to parent/all child products.
I have checked the disable setting for parent/all child products is set to "no".
I have clear all caches and re-indexed.

**Comment by kentpatrick** [comment]
I durped realised my mistake. Working fine now

**Comment by sprankhub** [comment]
Good to hear that it works now! If you do not mind, share your mistake, so that people can check this as well.

**Comment by kentpatrick** [comment]
It was a lack on understanding magentos system. when putting in my tiered price i did it as a total not per unit.
example if a Quaffle is £10 each my tiered setup would have been
3 @ £27
5 @ £42
corrected by the following
3 @ £9
5 @ £8
