### ISSUE TITLE
If I am on the cart and save a product in the admin that is in cart, I get a nested loop

### ISSUE THREAD

**Issue by paras89** [sprankhub/Spranks_ConfigurableTierPrices#31]
For some reason if I have a product in cart and save the product in admin panel - change price etc.
When I refresh the cart I get a nested loop error:

Mage_Core_Controller_Varien_Router_Standard->match( ) | .../Standard.php:91
7 | 0.0374 | 2484776 | Mage_Core_Controller_Varien_Action->dispatch( ) | .../Standard.php:254
8 | 0.0374 | 2484968 | Mage_Checkout_CartController->preDispatch( ) | .../Action.php:407
9 | 0.0483 | 3278144 | Mage_Checkout_Model_Cart->getQuote( ) | .../CartController.php:129
10 | 0.0485 | 3329728 | Mage_Checkout_Model_Session->getQuote( ) | .../Cart.php:119
11 | 0.0488 | 3437680 | Mage_Sales_Model_Quote->loadActive( ) | .../Session.php:127
12 | 0.0500 | 3499384 | Mage_Sales_Model_Quote->_afterLoad( ) | .../Quote.php:376
13 | 0.0500 | 3500224 | Mage_Sales_Model_Quote->collectTotals( ) | .../Quote.php:1907
14 | 0.1179 | 8541320 | Mage_Sales_Model_Quote_Address->collectTotals( ) | .../Quote.php:1331
15 | 0.1203 | 8552880 | Mage_Sales_Model_Quote_Address_Total_Subtotal->collect( ) | .../Address.php:1013
16 | 0.1204 | 8553968 | Mage_Sales_Model_Quote_Address_Total_Subtotal->_initItem( ) | .../Subtotal.php:48
17 | 0.1208 | 8555264 | Mage_Catalog_Model_Product->getFinalPrice( ) | .../Subtotal.php:115
18 | 0.1208 | 8555552 | Mage_Catalog_Model_Product_Type_Configurable_Price->getFinalPrice( ) | .../Product.php:712
19 | 0.2218 | 10158528 | Mage::dispatchEvent( ) | .../Price.php:52
20 | 0.2219 | 10158528 | Mage_Core_Model_App->dispatchEvent( ) | .../Mage.php:448
21 | 0.2219 | 10160384 | Mage_Core_Model_App->_callObserverMethod( ) | .../App.php:1337
22 | 0.2219 | 10160384 | Spranks_ConfigurableTierPrices_Model_Observer->catalogProductGetFinalPrice( ) | .../App.php:1358
23 | 0.2242 | 10160792 | Spranks_ConfigurableTierPrices_Model_Observer->_calcConfigProductTierPricing( ) | .../Observer.php:29
24 | 0.2242 | 10160960 | Spranks_ConfigurableTierPrices_Model_Observer->_getAllVisibleItems( ) | .../Observer.php:51
25 | 0.2242 | 10161048 | Mage_Checkout_Model_Session->getQuote( ) | .../Observer.php:85
26 | 0.2245 | 10161992 | Mage_Sales_Model_Quote->loadActive( ) | .../Session.php:127
27 | 0.2253 | 10171504 | Mage_Sales_Model_Quote->_afterLoad( ) | .../Quote.php:376
28 | 0.2253 | 10171504 | Mage_Sales_Model_Quote->collectTotals( ) | .../Quote.php:1907
29 | 0.2523 | 10345824 | Mage_Sales_Model_Quote_Address->collectTotals( ) | .../Quote.php:1331
30 | 0.2537 | 10358568 | Mage_Sales_Model_Quote_Address_Total_Subtotal->collect( ) | .../Address.php:1013
31 | 0.2537 | 10359008 | Mage_Sales_Model_Quote_Address_Total_Subtotal->_initItem( ) | .../Subtotal.php:48
32 | 0.2538 | 10359008 | Mage_Catalog_Model_Product->getFinalPrice( ) | .../Subtotal.php:115
33 | 0.2538 | 10359056 | Mage_Catalog_Model_Product_Type_Configurable_Price->getFinalPrice( ) | .../Product.php:712
34 | 0.2549 | 10359880 | Mage::dispatchEvent( ) | .../Price.php:52
35 | 0.2549 | 10359880 | Mage_Core_Model_App->dispatchEvent( ) | .../Mage.php:448
36 | 0.2550 | 10362464 | Mage_Core_Model_App->_callObserverMethod( ) | .../App.php:1337
37 | 0.2550 | 10362464 | Spranks_ConfigurableTierPrices_Model_Observer->catalogProductGetFinalPrice( ) | .../App.php:1358
38 | 0.2574 | 10362624 | Spranks_ConfigurableTierPrices_Model_Observer->_calcConfigProductTierPricing( ) | .../Observer.php:29
39 | 0.2574 | 10362672 | Spranks_ConfigurableTierPrices_Model_Observer->_getAllVisibleItems( ) | .../Observer.php:51
40 | 0.2574 | 10362672 | Mage_Checkout_Model_Session->getQuote( ) | .../Observer.php:85
41 | 0.2578 | 10363616 | Mage_Sales_Model_Quote->loadActive( ) | .../Session.php:127
42 | 0.2599 | 10373096 | Mage_Sales_Model_Quote->_afterLoad( ) | .../Quote.php:376
43 | 0.2599 | 10373096 | Mage_Sales_Model_Quote->collectTotals( ) | .../Quote.php:1907
44 | 0.2841 | 10547384 | Mage_Sales_Model_Quote_Address->collectTotals( ) | .../Quote.php:1331
45 | 0.2853 | 10560128 | Mage_Sales_Model_Quote_Address_Total_Subtotal->collect( ) | .../Address.php:1013
46 | 0.2853 | 10560568 | Mage_Sales_Model_Quote_Address_Total_Subtotal->_initItem( ) | .../Subtotal.php:48
47 | 0.2854 | 10560568 | Mage_Catalog_Model_Product->getFinalPrice( ) | .../Subtotal.php:115
48 | 0.2854 | 10560616 | Mage_Catalog_Model_Product_Type_Configurable_Price->getFinalPrice( ) | .../Product.php:712
49 | 0.2863 | 10561440 | Mage::dispatchEvent( ) | .../Price.php:52
50 | 0.2863 | 10561440 | Mage_Core_Model_App->dispatchEvent( ) | .../Mage.php:448
51 | 0.2864 | 10564024 | Mage_Core_Model_App->_callObserverMethod( ) | .../App.php:1337
52 | 0.2864 | 10564024 | Spranks_ConfigurableTierPrices_Model_Observer->catalogProductGetFinalPrice( ) | .../App.php:1358
53 | 0.2881 | 10564184 | Spranks_ConfigurableTierPrices_Model_Observer->_calcConfigProductTierPricing( ) | .../Observer.php:29
54 | 0.2881 | 10564232 | Spranks_ConfigurableTierPrices_Model_Observer->_getAllVisibleItems( ) | .../Observer.php:51
55 | 0.2881 | 10564232 | Mage_Checkout_Model_Session->getQuote( ) | .../Observer.php:85
56 | 0.2883 | 10565176 | Mage_Sales_Model_Quote->loadActive( ) | .../Session.php:127
57 | 0.2898 | 10574656 | Mage_Sales_Model_Quote->_afterLoad( ) | .../Quote.php:376
58 | 0.2898 | 10574656 | Mage_Sales_Model_Quote->collectTotals( ) | .../Quote.php:1907
59 | 0.3169 | 10748976 | Mage_Sales_Model_Quote_Address->collectTotals( ) | .../Quote.php:1331
60 | 0.3184 | 10761720 | Mage_Sales_Model_Quote_Address_Total_Subtotal->collect( ) | .../Address.php:1013
61 | 0.3184 | 10762160 | Mage_Sales_Model_Quote_Address_Total_Subtotal->_initItem( ) | .../Subtotal.php:48
62 | 0.3184 | 10762160 | Mage_Catalog_Model_Product->getFinalPrice( ) | .../Subtotal.php:115
63 | 0.3185 | 10762208 | Mage_Catalog_Model_Product_Type_Configurable_Price->getFinalPrice( ) | .../Product.php:712
64 | 0.3196 | 10763032 | Mage::dispatchEvent( ) | .../Price.php:52
65 | 0.3196 | 10763032 | Mage_Core_Model_App->dispatchEvent( ) | .../Mage.php:448
66 | 0.3196 | 10765616 | Mage_Core_Model_App->_callObserverMethod( ) | .../App.php:1337
67 | 0.3196 | 10765616 | Spranks_ConfigurableTierPrices_Model_Observer->catalogProductGetFinalPrice( ) | .../App.php:1358
68 | 0.3217 | 10765776 | Spranks_ConfigurableTierPrices_Model_Observer->_calcConfigProductTierPricing( ) | .../Observer.php:29
69 | 0.3217 | 10765824 | Spranks_ConfigurableTierPrices_Model_Observer->_getAllVisibleItems( ) | .../Observer.php:51
70 | 0.3218 | 10765824 | Mage_Checkout_Model_Session->getQuote( ) | .../Observer.php:85
71 | 0.3220 | 10766768 | Mage_Sales_Model_Quote->loadActive( ) | .../Session.php:127
72 | 0.3228 | 10776248 | Mage_Sales_Model_Quote->_afterLoad( ) | .../Quote.php:376
73 | 0.3228 | 10776248 | Mage_Sales_Model_Quote->collectTotals( ) | .../Quote.php:1907
74 | 0.3506 | 10950624 | Mage_Sales_Model_Quote_Address->collectTotals( ) | .../Quote.php:1331
75 | 0.3526 | 10963368 | Mage_Sales_Model_Quote_Address_Total_Subtotal->collect( ) | .../Address.php:1013
76 | 0.3527 | 10963808 | Mage_Sales_Model_Quote_Address_Total_Subtotal->_initItem( ) | .../Subtotal.php:48
77 | 0.3527 | 10963808 | Mage_Catalog_Model_Product->getFinalPrice( ) | .../Subtotal.php:115
78 | 0.3528 | 10963856 | Mage_Catalog_Model_Product_Type_Configurable_Price->getFinalPrice( ) | .../Product.php:712
79 | 0.3542 | 10964680 | Mage::dispatchEvent( ) | .../Price.php:52
80 | 0.3542 | 10964680 | Mage_Core_Model_App->dispatchEvent( ) | .../Mage.php:448
81 | 0.3542 | 10967264 | Mage_Core_Model_App->_callObserverMethod( ) | .../App.php:1337
82 | 0.3542 | 10967264 | Spranks_ConfigurableTierPrices_Model_Observer->catalogProductGetFinalPrice( ) | .../App.php:1358
83 | 0.3572 | 10967424 | Spranks_ConfigurableTierPrices_Model_Observer->_calcConfigProductTierPricing( ) | .../Observer.php:29
84 | 0.3572 | 10967472 | Spranks_ConfigurableTierPrices_Model_Observer->_getAllVisibleItems( ) | .../Observer.php:51
85 | 0.3572 | 10967472 | Mage_Checkout_Model_Session->getQuote( ) | .../Observer.php:85
86 | 0.3577 | 10968416 | Mage_Sales_Model_Quote->loadActive( ) | .../Session.php:127
87 | 0.3595 | 10977896 | Mage_Sales_Model_Quote->_afterLoad( ) | .../Quote.php:376
88 | 0.3595 | 10977896 | Mage_Sales_Model_Quote->collectTotals( ) | .../Quote.php:1907
89 | 0.3849 | 11152208 | Mage_Sales_Model_Quote_Address->collectTotals( ) | .../Quote.php:1331
90 | 0.3866 | 11164952 | Mage_Sales_Model_Quote_Address_Total_Subtotal->collect( ) | .../Address.php:1013
91 | 0.3866 | 11165392 | Mage_Sales_Model_Quote_Address_Total_Subtotal->_initItem( ) | .../Subtotal.php:48
92 | 0.3867 | 11165392 | Mage_Catalog_Model_Product->getFinalPrice( ) | .../Subtotal.php:115
93 | 0.3867 | 11165440 | Mage_Catalog_Model_Product_Type_Configurable_Price->getFinalPrice( )

**Comment by paras89** [comment]
As can be seen in the stack trace, Magento is going into a collect totals loop.

**Comment by paras89** [comment]
On further inspection I have found that the quote table has a column called - trigger_recollect, which is set to 1 when a product in the quote is saved in admin. This flag is then used on quote after load method to calculate totals. This causes the extension observer to result in a loop of calling getFinalPrice 

It would be great if you could provide a fix for this.

**Comment by sprankhub** [comment]
Could you please download the current master branch and check if the issue persists? I cannot reproduce the issue with the latest master branch.
